repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        files: ^(include|src|app)/.*\.(c|cc|cpp|cxx|h|hpp)$

  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        files: ^(include|src|app)/.*\.(c|cc|cpp|cxx|h|hpp)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        files: ^user/.*\.py$
      - id: ruff-format
        files: ^user/.*\.py$

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        files: \.sh(\.in)?$
        exclude: ^scripts/alidist/scirooplot\.sh$
