#!/usr/bin/env python3
"""Generates docs/skill/scirooplot/reference/api.md from the public interface in include/SciRooPlot.

The file lists every public method of the user-facing classes, one per line, as declared in the headers.
It is committed to the repository; the CI compares it with a freshly generated version so that it cannot drift.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADERS = ["Plot.h", "PlotManager.h", "PanelLayout.h"]
OUTPUT = ROOT / "docs/skill/scirooplot/reference/api.md"
OPTIONS_OUTPUT = ROOT / "docs/skill/scirooplot/reference/drawing-options.md"

# classes in the order they are listed; (header, declaration, title, remark)
CLASSES = [
    ("PlotManager.h", "class PlotManager", "PlotManager", "central object: data sources, plots, base plots, project files"),
    ("Plot.h", "class Plot", "Plot", "plot[padID] gives the Pad (padID 0: defaults for all pads)"),
    ("Plot.h", "class Plot::Pad", "Plot::Pad", "pad[axis] gives the Axis ('X', 'Y', 'Z'); pad(dataID) the Data (counting from 1)"),
    ("Plot.h", "class Plot::Pad::Axis", "Plot::Pad::Axis", ""),
    ("Plot.h", "class Plot::Pad::Data", "Plot::Pad::Data", "every setter returns the Data, so calls can be chained"),
    ("Plot.h", "class Plot::Pad::Ratio", "Plot::Pad::Ratio", "has all setters, modifiers and selections of Data (returning the Ratio) plus the following"),
    ("Plot.h", "class Plot::Pad::Box", "Plot::Pad::Box<BoxType>", "common to TextBox and LegendBox"),
    ("Plot.h", "class Plot::Pad::TextBox", "Plot::Pad::TextBox", ""),
    ("Plot.h", "class Plot::Pad::LegendBox", "Plot::Pad::LegendBox", ""),
    ("Plot.h", "class Plot::Pad::LegendBox::LegendEntry", "Plot::Pad::LegendBox::LegendEntry", ""),
    ("PanelLayout.h", "class Panel", "Panel", "a cell of a PanelLayout, in units of the standard panel; `Gap()` separates independent panels, `Empty()` leaves a cell without axes"),
    ("PanelLayout.h", "class PanelLayout", "PanelLayout", "arrangement of panels and the sizes shared by all base plots"),
]

METHOD = re.compile(r"^\s*(?:virtual\s+|static\s+|explicit\s+)*(?:(?P<ret>[\w:<>&\*,\s]+?)\s+)?(?P<name>\w+)\((?P<args>.*)\)\s*(?:const\s*)?(?:override\s*)?(?:=\s*default\s*)?(?:\{.*\}|;)")
SKIP_NAMES = {"Print", "GetPropertyTree", "GetTree", "SetTree", "operator=", "Clone"}
# argument types that are built from literals in user code
TYPES = {
    "data_dim_t": '`"var"` (100 automatic bins), `{"var", nBins}`, `{"var", nBins, {min, max}}` or `{"var", {edges...}}` (Python: tuples)',
    "join_tree_t": '`"tree"` (same data source) or `{"tree", "dataSource"}` (Python: list)',
}


def public_section(text: str, declaration: str) -> str:
    """the public part of the class body (up to the first protected/private label)"""
    start = text.find(declaration + "\n")
    if start < 0:
        start = text.find(declaration + " ")
    if start < 0:
        sys.exit(f"{declaration} not found")
    body = text[start:]
    end = re.search(r"^\s*(protected|private):", body, re.M)
    return body[: end.start()] if end else body


def methods(section: str, class_name: str):
    result = []
    # join declarations that span several lines
    lines = []
    for line in section.splitlines():
        if lines and not re.search(r"[;{}]\s*(//.*)?$", lines[-1]) and not lines[-1].strip().startswith("//"):
            lines[-1] = lines[-1].rstrip() + " " + line.strip()
        else:
            lines.append(line)
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith(("//", "#", "friend", "using", "template", "class", "struct", "enum")):
            continue
        match = METHOD.match(line)
        if not match:
            continue
        name = match["name"]
        if name in SKIP_NAMES or name.startswith("Get") and name not in {"GetAxis", "GetData", "GetLegend", "GetText", "GetEntry", "GetProjectProperty", "GetPad"}:
            continue  # plain getters are not part of the user interface
        ret = (match["ret"] or "").strip()
        args = re.sub(r"\s+", " ", match["args"].strip())
        short = class_name.split("::")[-1].split("<")[0]
        if "ptree" in args or args in (f"const {short}& other", f"{short}&&") or name.endswith("_t"):
            continue  # internal, copy and move constructors; helper structs are described in TYPES
        comment = ""
        if "//" in line:
            comment = line.split("//", 1)[1].strip()
        if ret == "" and name == class_name.split("::")[-1].split("<")[0]:
            result.append((f"{name}({args})", comment, True))
        else:
            result.append((f"{ret} {name}({args})", comment, False))
    return result


def main():
    texts = {h: (ROOT / "include/SciRooPlot" / h).read_text() for h in HEADERS}
    out = [
        "# SciRooPlot API reference",
        "",
        "Generated by `scripts/generate-api-reference.py` from the headers in `include/SciRooPlot` — do not edit by hand.",
        "Types: `std::optional<T>` arguments can be left out (Python: `None`); `std::vector` arguments take `{...}` in C++ and lists in Python;",
        "`drawing_options_t` is one of the aliases listed in `drawing-options.md`; colours, styles and fonts are ROOT constants (`kRed + 1`, `kFullCircle`, `kDashed`, 43).",
        "",
    ]
    for header, declaration, title, remark in CLASSES:
        section = public_section(texts[header], declaration)
        out.append(f"## {title}")
        if remark:
            out.append(f"*{remark}*")
        out.append("")
        used_types = set()
        for signature, comment, is_ctor in methods(section, title):
            line = f"- `{signature}`"
            if comment:
                line += f" — {comment}"
            out.append(line)
            used_types |= {t for t in TYPES if t in signature}
        for t in sorted(used_types):
            out.append(f"- `{t}`: {TYPES[t]}")
        out.append("")
    # the drawing option aliases and placements are part of the interface too
    block = texts["Plot.h"][texts["Plot.h"].index("#define DRAWING_OPTIONS") : texts["Plot.h"].index("enum drawing_options_t")]
    aliases = re.findall(r"OPT\((\w+)", block)
    out += ["## Enumerations", "", "- `drawing_options_t`: " + ", ".join(f"`{a}`" for a in aliases), "- `box_placement_t`: `best_corner`, `top_left`, `top_right`, `bottom_right`, `bottom_left`", ""]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    for path, content in ((OUTPUT, "\n".join(out)), (OPTIONS_OUTPUT, drawing_options(aliases))):
        if "--check" in sys.argv:
            if not path.exists() or path.read_text() != content:
                sys.exit(f"{path.relative_to(ROOT)} is outdated: run scripts/generate-api-reference.py")
            continue
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


def drawing_options(aliases):
    """alias -> ROOT option string per data type, from the maps in src/PlotPainter.h"""
    text = (ROOT / "src/PlotPainter.h").read_text()
    maps = {}
    for name in ("Hist", "Graph", "Hist2d"):
        block = text[text.index(f"defaultDrawingOptions_{name}{{") :]
        block = block[: block.index("};")]
        maps[name] = {alias: option for alias, option in re.findall(r"\{(\w+), \"([^\"]*)\"\}", block)}
    out = [
        "# SciRooPlot drawing option aliases",
        "",
        "Generated by `scripts/generate-api-reference.py` from `src/PlotPainter.h` — do not edit by hand.",
        "`SetOptions(<alias>)` expands to the ROOT drawing option of the data type; `SetOptions(\"<string>\")` passes a raw ROOT option instead.",
        "Histograms and graphs share all 1D aliases: where ROOT has no option for one of them, the data is converted and drawn as the other type",
        "(*as graph* / *as histogram*). An alias a type cannot draw at all gives a WARNING and ROOT's default.",
        "",
        "| alias | 1D histogram | graph | 2D histogram |",
        "|---|---|---|---|",
    ]
    for alias in aliases:
        h, g, h2 = maps["Hist"].get(alias), maps["Graph"].get(alias), maps["Hist2d"].get(alias)
        if h is None and g is not None:
            h = "*as graph*"
        elif g is None and h is not None:
            g = "*as histogram*"
        cells = [f"`{o}`" if o and not o.startswith("*") else (o or "–") for o in (h, g, h2)]
        out.append(f"| `{alias}` | {' | '.join(cells)} |")
    out += [
        "",
        "Appearance details beyond the ROOT string: `points`, `points_endcaps`, `points_line`, `points_text`, `points_arrows` hide the x errors of graphs (as X0 does for histograms);",
        "`points_text` writes the values above the error bars; `boxes_nomarkers` removes the markers; `line`/`curve` of histograms are not filled;",
        "`area` of graphs is the polygon between the points and zero; `candle` is ROOT preset 2 (box, median, whiskers at 1.5 IQR, outliers), `candle_minmax` preset 1 (whiskers to the extremes).",
        "",
    ]
    return "\n".join(out)


if __name__ == "__main__":
    main()
