theme: jekyll-theme-cayman

include:
  - slides

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

defaults:
  - scope:
      path: _docs
      type: docs
    values:
      layout: docs
