theme: jekyll-theme-cayman
collections:
    docs:
      permalink: "/:collection/:path/"
      output: true
defaults:
    - scope:
        path: _docs
        type: docs
      values:
        layout: docs