name: Code Quality

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
